<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CTU-PSU" ignored="0" name="Regression1" tests="3" failures="1" timestamp="2019-10-11T16:27:56 CST" time="0.03" errors="0">
  <testcase name="test1" time="0.0" classname="casest.BasicCase"/>
  <testcase name="test2" time="0.002" classname="casest.BasicCase">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at casest.BasicCase.test2(BasicCase.java:36)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at com.sun.proxy.$Proxy2.stop(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 50 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.0" classname="casest.BasicCase"/>
</testsuite> <!-- Regression1 -->
